### ISSUE TITLE
Are you planning to support ligatures?

### ISSUE THREAD

**Issue by hoichi** [sursly/leaguemono#1]
I know it’s a mashup of Fira _Mono_, not Fira _Code_, but still, the reason I prefer Fira Code to a lot of other monospace fonts is ligatures. Are those in the plans for League Mono?

**Comment by sursly** [comment]
@hoichi - I don't think so, only because I haven't run in to a pair that would benefit from a ligature. The natural spacing in League Mono (even when set in bold) would make that somewhat superfluous. I'm not against it though, but I'm not planning on adding any (though as this is open source, someone else could).
